import type { League } from './leagues';
import type { OpponentResponse } from './match';

/**
 * "Beat the legends": 40 legendary club seasons of the top five leagues since 1960, each a boss
 * your XI can take on once per squad. The server finds the club season by league, season and a
 * slug pattern (club slugs differ in spelling), then plays its real likely XI.
 */

export type Legend = {
  id: string;
  club: string;
  league: League;
  /** Start year of the season (1988 = 1988/89). */
  season: number;
  /** Short name of the team, e.g. "Sacchi's Milan". */
  nickname: string;
  /** Why the season is legendary (one line). */
  story: string;
  /** Regular expression for the club slug in our data. */
  slug: string;
  /** Slug pattern that must not match (Milan vs Inter). */
  notSlug?: string;
  /** 1 = tough … 3 = the very best. */
  tier: 1 | 2 | 3;
};

export const LEGENDS: Legend[] = [
  {
    id: 'milan-1988',
    club: 'AC Milan',
    league: 'ITA',
    season: 1988,
    nickname: "Sacchi's Milan",
    story: 'Gullit, Van Basten, Rijkaard, Baresi – pressing that changed football, European Cup winners.',
    slug: 'milan',
    notSlug: 'inter',
    tier: 3,
  },
  {
    id: 'milan-1993',
    club: 'AC Milan',
    league: 'ITA',
    season: 1993,
    nickname: "Capello's Milan",
    story: 'The 4–0 over Barcelona in Athens and a defence that barely conceded.',
    slug: 'milan',
    notSlug: 'inter',
    tier: 3,
  },
  {
    id: 'barcelona-2008',
    club: 'Barcelona',
    league: 'ESP',
    season: 2008,
    nickname: "Guardiola's first treble",
    story: 'Xavi, Iniesta, Messi – the first Spanish treble, 2–6 at the Bernabéu.',
    slug: 'barcelona',
    tier: 3,
  },
  {
    id: 'barcelona-2010',
    club: 'Barcelona',
    league: 'ESP',
    season: 2010,
    nickname: 'The Wembley side',
    story: 'Often called the best club team ever: 5–0 in the Clásico, 3–1 in the Wembley final.',
    slug: 'barcelona',
    tier: 3,
  },
  {
    id: 'barcelona-2014',
    club: 'Barcelona',
    league: 'ESP',
    season: 2014,
    nickname: 'MSN',
    story: 'Messi, Suárez and Neymar: 122 goals between them and a second treble.',
    slug: 'barcelona',
    tier: 3,
  },
  {
    id: 'real-2013',
    club: 'Real Madrid',
    league: 'ESP',
    season: 2013,
    nickname: 'La Décima',
    story: 'Ramos in the 93rd minute in Lisbon – the tenth European Cup.',
    slug: 'real-madrid',
    tier: 2,
  },
  {
    id: 'real-2016',
    club: 'Real Madrid',
    league: 'ESP',
    season: 2016,
    nickname: "Zidane's double",
    story: 'League and back-to-back Champions Leagues, Cristiano at his most decisive.',
    slug: 'real-madrid',
    tier: 3,
  },
  {
    id: 'real-2001',
    club: 'Real Madrid',
    league: 'ESP',
    season: 2001,
    nickname: 'Galácticos',
    story: "Zidane's Hampden volley, Figo, Raúl, Roberto Carlos – the ninth European Cup.",
    slug: 'real-madrid',
    tier: 2,
  },
  {
    id: 'bayern-2012',
    club: 'Bayern Munich',
    league: 'GER',
    season: 2012,
    nickname: "Heynckes' treble",
    story: '91 points, 7–0 on aggregate over Barcelona, Robben at Wembley.',
    slug: 'bayern',
    tier: 3,
  },
  {
    id: 'bayern-2019',
    club: 'Bayern Munich',
    league: 'GER',
    season: 2019,
    nickname: "Flick's sextuple",
    story: '8–2 against Barcelona and every trophy on offer.',
    slug: 'bayern',
    tier: 3,
  },
  {
    id: 'bayern-1973',
    club: 'Bayern Munich',
    league: 'GER',
    season: 1973,
    nickname: 'Beckenbauer & Müller',
    story: 'The first of three European Cups in a row, with Maier, Breitner and Hoeneß.',
    slug: 'bayern',
    tier: 2,
  },
  {
    id: 'arsenal-2003',
    club: 'Arsenal',
    league: 'ENG',
    season: 2003,
    nickname: 'The Invincibles',
    story: '38 league games, not one defeat – Henry, Vieira, Pirès, Bergkamp.',
    slug: 'arsenal',
    tier: 3,
  },
  {
    id: 'manutd-1998',
    club: 'Manchester United',
    league: 'ENG',
    season: 1998,
    nickname: 'Treble winners',
    story: 'Two goals in stoppage time at the Camp Nou and the only English treble of its time.',
    slug: 'manchester-united|man-united|man-utd',
    tier: 3,
  },
  {
    id: 'manutd-2007',
    club: 'Manchester United',
    league: 'ENG',
    season: 2007,
    nickname: 'Ronaldo, Rooney, Tévez',
    story: 'League and Champions League in the rain of Moscow.',
    slug: 'manchester-united|man-united|man-utd',
    tier: 2,
  },
  {
    id: 'liverpool-1983',
    club: 'Liverpool',
    league: 'ENG',
    season: 1983,
    nickname: 'The treble of 1984',
    story: 'League, League Cup and the European Cup in Rome – Rush, Dalglish, Souness.',
    slug: 'liverpool',
    tier: 2,
  },
  {
    id: 'liverpool-2019',
    club: 'Liverpool',
    league: 'ENG',
    season: 2019,
    nickname: "Klopp's champions",
    story: 'The 30-year wait ends: 99 points and a 27-game winning run at home.',
    slug: 'liverpool',
    tier: 3,
  },
  {
    id: 'city-2017',
    club: 'Manchester City',
    league: 'ENG',
    season: 2017,
    nickname: 'The Centurions',
    story: '100 points, 106 goals – the first 100-point season in top-flight England.',
    slug: 'manchester-city|man-city',
    tier: 3,
  },
  {
    id: 'city-2022',
    club: 'Manchester City',
    league: 'ENG',
    season: 2022,
    nickname: "Haaland's treble",
    story: 'Haaland scores 36 league goals, City finally win Europe in Istanbul.',
    slug: 'manchester-city|man-city',
    tier: 3,
  },
  {
    id: 'chelsea-2004',
    club: 'Chelsea',
    league: 'ENG',
    season: 2004,
    nickname: "Mourinho's first",
    story: '95 points and only 15 goals conceded – Terry, Lampard, Drogba, Čech.',
    slug: 'chelsea',
    tier: 2,
  },
  {
    id: 'leicester-2015',
    club: 'Leicester City',
    league: 'ENG',
    season: 2015,
    nickname: 'The 5000–1 miracle',
    story: 'Vardy, Mahrez and Kanté win the league nobody believed in.',
    slug: 'leicester',
    tier: 1,
  },
  {
    id: 'forest-1978',
    club: 'Nottingham Forest',
    league: 'ENG',
    season: 1978,
    nickname: "Clough's Forest",
    story: 'Promoted, champions, then European champions – twice in a row.',
    slug: 'nottingham',
    tier: 1,
  },
  {
    id: 'inter-2009',
    club: 'Inter Milan',
    league: 'ITA',
    season: 2009,
    nickname: "Mourinho's treble",
    story: 'Sneijder, Milito, Zanetti and the Madrid final – the only Italian treble.',
    slug: 'inter',
    tier: 2,
  },
  {
    id: 'inter-1964',
    club: 'Inter Milan',
    league: 'ITA',
    season: 1964,
    nickname: 'Grande Inter',
    story: "Herrera's catenaccio, Facchetti, Mazzola, Suárez – two European Cups in a row.",
    slug: 'inter',
    tier: 2,
  },
  {
    id: 'juventus-1984',
    club: 'Juventus',
    league: 'ITA',
    season: 1984,
    nickname: "Platini's Juve",
    story: 'Platini, Boniek, Scirea, Cabrini – the European Cup and three Ballon d’Ors in a row for Platini.',
    slug: 'juventus',
    tier: 2,
  },
  {
    id: 'juventus-1995',
    club: 'Juventus',
    league: 'ITA',
    season: 1995,
    nickname: "Lippi's Juve",
    story: 'Del Piero, Vialli, Ravanelli – Champions League winners in Rome.',
    slug: 'juventus',
    tier: 2,
  },
  {
    id: 'juventus-2013',
    club: 'Juventus',
    league: 'ITA',
    season: 2013,
    nickname: 'The 102-point Juve',
    story: "Conte's record season: 102 points, Pirlo, Pogba, Vidal.",
    slug: 'juventus',
    tier: 2,
  },
  {
    id: 'napoli-1986',
    club: 'Napoli',
    league: 'ITA',
    season: 1986,
    nickname: "Maradona's Napoli",
    story: 'The first scudetto in the south, a city dancing for Diego.',
    slug: 'napoli',
    tier: 2,
  },
  {
    id: 'napoli-2022',
    club: 'Napoli',
    league: 'ITA',
    season: 2022,
    nickname: 'Kvara & Osimhen',
    story: 'A third scudetto, 33 years after Maradona, won by a mile.',
    slug: 'napoli',
    tier: 1,
  },
  {
    id: 'sampdoria-1990',
    club: 'Sampdoria',
    league: 'ITA',
    season: 1990,
    nickname: 'Vialli & Mancini',
    story: 'The goal twins bring Sampdoria its only scudetto.',
    slug: 'sampdoria',
    tier: 1,
  },
  {
    id: 'leverkusen-2023',
    club: 'Bayer Leverkusen',
    league: 'GER',
    season: 2023,
    nickname: 'Neverkusen no more',
    story: "Xabi Alonso's unbeaten champions – 28 wins, 6 draws, 0 defeats.",
    slug: 'leverkusen',
    tier: 2,
  },
  {
    id: 'dortmund-1996',
    club: 'Borussia Dortmund',
    league: 'GER',
    season: 1996,
    nickname: 'Munich 1997',
    story: 'Riedle, Sammer, Möller and Ricken’s lob – Champions League winners over Juventus.',
    slug: 'dortmund',
    tier: 1,
  },
  {
    id: 'dortmund-2011',
    club: 'Borussia Dortmund',
    league: 'GER',
    season: 2011,
    nickname: "Klopp's double",
    story: 'Record 81 points, Lewandowski, Götze, Hummels – and the cup.',
    slug: 'dortmund',
    tier: 2,
  },
  {
    id: 'gladbach-1975',
    club: 'Borussia Mönchengladbach',
    league: 'GER',
    season: 1975,
    nickname: 'The Foals',
    story: 'Netzer’s heirs Heynckes, Vogts, Bonhof, Simonsen – five titles in the 70s.',
    slug: 'gladbach',
    tier: 1,
  },
  {
    id: 'hamburg-1982',
    club: 'Hamburger SV',
    league: 'GER',
    season: 1982,
    nickname: 'Europe’s best',
    story: 'Magath’s strike in Athens beats Juventus – HSV on top of Europe.',
    slug: 'hamburg',
    tier: 1,
  },
  {
    id: 'marseille-1992',
    club: 'Marseille',
    league: 'FRA',
    season: 1992,
    nickname: 'OM in Munich',
    story: 'Boli’s header beats Milan – the first French European champions.',
    slug: 'marseille',
    tier: 2,
  },
  {
    id: 'psg-2015',
    club: 'Paris Saint-Germain',
    league: 'FRA',
    season: 2015,
    nickname: 'Zlatan’s last season',
    story: 'Ibrahimović scores 38 league goals, the title won by 31 points.',
    slug: 'paris|psg',
    tier: 2,
  },
  {
    id: 'saint-etienne-1975',
    club: 'Saint-Étienne',
    league: 'FRA',
    season: 1975,
    nickname: 'Les Verts',
    story: 'The square posts of Glasgow – the green legend of French football.',
    slug: 'etienne',
    tier: 1,
  },
  {
    id: 'lyon-2005',
    club: 'Lyon',
    league: 'FRA',
    season: 2005,
    nickname: 'The seven-in-a-row Lyon',
    story: 'Juninho’s free kicks and a fifth straight title on the way to seven.',
    slug: 'lyon',
    tier: 1,
  },
  {
    id: 'atletico-2013',
    club: 'Atlético Madrid',
    league: 'ESP',
    season: 2013,
    nickname: "Simeone's title",
    story: 'Champions ahead of Barça and Real on the last day at the Camp Nou.',
    slug: 'atletico',
    tier: 2,
  },
  {
    id: 'valencia-2003',
    club: 'Valencia',
    league: 'ESP',
    season: 2003,
    nickname: "Benítez's Valencia",
    story: 'League and UEFA Cup – Ayala, Baraja, Albelda, Vicente.',
    slug: 'valencia',
    tier: 1,
  },
];

export const legendById = (id: string) => LEGENDS.find((l) => l.id === id) ?? null;

/** GET /api/legend?id=… – the legend season's likely XI (an opponent XI plus the legend id). */
export type LegendResponse = OpponentResponse & { legendId: string };

/** GET /api/legends – which legends have a squad in the database (the others can't be played yet). */
export type LegendsAvailability = { available: string[] };
